### ISSUE TITLE
cant get it to work

### ISSUE THREAD

**Issue by gianfr80** [mondul/hekate_boot_dat#1]
hi, im new to this, i installed phyton 3. dropped the hetake file over the script. it creates a boot.dat file, but its empty
do i need to do anything else?

**Comment by mondul** [comment]
Hi, sorry for the late response. The .py was modified to work when `payload.bin`  is in the same directory, so that's all you need to do. For more info on how it runs you can check the workflow file that generates the resulting boot.dat. Also you can just extract [this file](https://github.com/mondul/MakeNSWSD-GUI/raw/main/sxgearboot.zip) at the root of your SD card and it will work every time after updates.
